
export const Projects = [{
    projectTitle: "Project 1",
    startDate: "2024-01-01T00:00:00",
    endDate: "2024-05-01-T00:00:00",
    description:"HDFC Features Upgrade",
    teams:["UI/UX","Applications","Connect","QA"],
    isInprogress:false,
    started:true,
    projectId:"asv1"
},
{
    projectTitle: "Project 2",
    startDate: "2024-06-01T00:00:00",
    endDate: "2024-10-01-T00:00:00",
    description:"ICICI Features Upgrade",
    teams:["UI/UX","Applications","Data Team","QA"],
    isInprogress:false,
    started:false,
    projectId:"asv2"
}];

export const tasksList = [{
    projectId:"asv1",
    projectName:"Project1",
    id: "task1",
    title: "Create a basic app for E-commerce feature to be integrated in current app",
    statusId:"status1",
    status: "TODO",
    description: "This is description",
    certificationRequired: true,
    label:"10_June_Release",
    reporter:"Rajeev Gupta",
    team: "UI/UX",
    teamId : "team1",
    creationDate: new Date(),
    endDate: new Date(),
    type: "Bug"
},
{
    projectId:"asv1",
    projectName:"Project1",
    id: "task2",
    title: "Create a layout for E-commerce feature",
    statusId:"status2",
    status: "In Progress",
    description: "This is description",
    certificationRequired: true,
    label:"10_June_Release",
    reporter:"Rajeev Gupta",
    team: "UI/UX",
    teamId : "team1",
    creationDate: new Date(),
    endDate: new Date(),
    type: "Story"
    },
{
    projectId:"asv1",
    projectName:"Project1",
    id: "task3",
    title: "Create a layout for E-commerce feature",
    statusId:"status2",
    status: "Review",
    description: "This is description",
    certificationRequired: true,
    label:"10_June_Release",
    reporter:"Rajeev Gupta",
    team: "UI/UX",
    teamId : "team1",
    creationDate: new Date(),
    endDate: new Date(),
    type: "Story"
    },
{
    projectId:"asv1",
    projectName:"Project1",
    id: "task4",
    title: "Create a layout for E-commerce feature",
    statusId:"status2",
    status: "Review",
    description: "This is description",
    certificationRequired: true,
    label:"10_June_Release",
    reporter:"Rajeev Gupta",
    team: "UI/UX",
    teamId : "team1",
    creationDate: new Date(),
    endDate: new Date(),
    type: "Story"
},
{
    projectId:"asv2",
    projectName:"Project1",
    id: "task5",
    title: "Create a layout for E-commerce feature",
    statusId:"status2",
    status: "Testing",
    description: "This is description",
    certificationRequired: true,
    label:"10_June_Release",
    reporter:"Rajeev Gupta",
    team: "UI/UX",
    teamId : "team1",
    creationDate: new Date(),
    endDate: new Date(),
    type: "Story"
}]